apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-cloud-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-cloud-api
  template:
    metadata:
      labels:
        app: go-cloud-api
    spec:
      containers:
        - name: go-cloud-api
          image: nadsonoliveiradev/go-cloud-api:latest
          ports:
            - containerPort: 3000 
          env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: go-cloud-secrets
                  key: PGHOST
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: go-cloud-secrets
                  key: PGPORT
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: go-cloud-secrets
                  key: PGUSER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: go-cloud-secrets
                  key: PGPASSWORD
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: go-cloud-secrets
                  key: PGDATABASE
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: go-cloud-secrets
                  key: DATABASE_URL
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: go-cloud-secrets
                  key: BASE_URL
            - name: PORT
              value: "3000"
